version: '3'
services:
    # Simple blog api
    simple_blog:
      depends_on:
        - postgres_db
      build: ./
      image: "anshulgupta/simple_blog"
      environment:
        - POSTGRES_HOST=postgres_db
        - POSTGRES_PORT=5432
        - POSTGRES_USERNAME=postgres
        - POSTGRES_PASSWORD=postgres_password
        - POSTGRES_DB=simple_blog_api
      ports:
        - "3000:3000"

    # Postgres database
    postgres_db:
      image: "postgres"
      environment:
        - POSTGRES_PASSWORD=postgres_password
        - POSTGRES_DB=simple_blog_api  
      
